import React, { useEffect, useMemo, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { NativeStackScreenProps } from '@react-navigation/native-stack';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { AnimatedNeonBackground } from '../components/AnimatedNeonBackground';
import { GridBackground } from '../components/GridBackground';
import { ScreenTopBar } from '../components/ScreenTopBar';
import type { RootStackParamList } from '../navigation/navigationTypes';
import { colors, fontFamilies, neonGlow, radii, withAlpha } from '../theme';

type Props = NativeStackScreenProps<RootStackParamList, 'LegalInfo'>;

type SectionKey = 'privacy' | 'terms' | 'data' | 'licenses';

const SECTIONS: Array<{ key: SectionKey; label: string }> = [
  { key: 'privacy', label: 'Privacy' },
  { key: 'terms', label: 'Terms' },
  { key: 'data', label: 'Data' },
  { key: 'licenses', label: 'Licenses' },
];

const ACCENT = colors.electricBlue;

const CONTENT: Record<SectionKey, string> = {
  privacy: [
    'DRAFT — Privacy (local-only beta)',
    '',
    'Number Rush currently stores gameplay progress, settings, missions, and soft-currency inventory on your device via local storage.',
    '',
    'There are no Number Rush user accounts, cloud sync, advertising SDKs, or in-app purchase backends in this beta.',
    '',
    'Ranked and Leaderboard screens are Coming Soon stubs and do not send competitive data online.',
    '',
    'See docs/privacy-policy-draft.md for the fuller DRAFT. A hosted policy URL is required before production store release.',
  ].join('\n'),
  terms: [
    'DRAFT — Terms of Use',
    '',
    'The App is provided as a local single-player puzzle entertainment product.',
    '',
    'Virtual coins, gems, power-ups, themes, and XP have no real-world cash value and are not redeemable for money.',
    '',
    'Classic and Daily modes work on-device. Ranked matchmaking and global leaderboards are not available in this beta.',
    '',
    'THE APP IS PROVIDED “AS IS” WITHOUT WARRANTIES OF ANY KIND TO THE MAXIMUM EXTENT PERMITTED BY LAW.',
    '',
    'See docs/terms-draft.md for the fuller DRAFT.',
  ].join('\n'),
  data: [
    'DRAFT — Data inventory summary',
    '',
    'On-device: scores, XP, coins, gems, inventory, themes, daily attempt state, missions, settings, tutorial flag, local economy transaction IDs.',
    '',
    'Libraries that may touch device capabilities: Expo runtime, AsyncStorage, React Navigation, fonts, expo-audio, expo-haptics, slider, SVG, linear-gradient.',
    '',
    'No analytics vendor, crash vendor, ads, IAP, or auth SDK is wired for remote collection by default.',
    '',
    'Beta feedback uses the OS Share sheet only — it does not POST to a Number Rush server.',
    '',
    'See docs/data-inventory.md.',
  ].join('\n'),
  licenses: [
    'DRAFT — Third-party notices',
    '',
    'This project depends on Expo, React Native, React Navigation, AsyncStorage, expo-audio, expo-haptics, expo-font, expo-linear-gradient, react-native-svg, community slider, Lucide icons, and related open-source packages.',
    '',
    'Repository LICENSE currently reflects the Expo MIT notice template present in the project root — replace with the product publisher license before store release if different.',
    '',
    'Placeholder audio assets are original synthesized tones generated by scripts/generateAudioAssets.mjs (not commercial game samples).',
    '',
    'Full dependency licenses are available from each package’s LICENSE file in node_modules / upstream repositories.',
  ].join('\n'),
};

export function LegalInfoScreen({ navigation, route }: Props) {
  const insets = useSafeAreaInsets();
  const initial = route.params?.section ?? 'privacy';
  const [section, setSection] = useState<SectionKey>(initial);

  useEffect(() => {
    if (route.params?.section) {
      setSection(route.params.section);
    }
  }, [route.params?.section]);

  const body = useMemo(() => CONTENT[section], [section]);

  return (
    <View style={[styles.root, { paddingTop: insets.top }]} testID="screen-legal">
      <View style={[styles.decor, { pointerEvents: 'none' }]}>
        <GridBackground opacity={0.04} />
        <AnimatedNeonBackground intensity="menu" />
      </View>

      <ScreenTopBar
        title="LEGAL (DRAFT)"
        accent={ACCENT}
        onBack={() => {
          if (navigation.canGoBack()) navigation.goBack();
          else navigation.navigate('Settings');
        }}
      />

      <View style={styles.tabs}>
        {SECTIONS.map(({ key, label }) => {
          const on = key === section;
          return (
            <Pressable
              key={key}
              testID={`legal-tab-${key}`}
              onPress={() => setSection(key)}
              style={[
                styles.tab,
                on && {
                  borderColor: ACCENT,
                  backgroundColor: withAlpha(ACCENT, 0.16),
                },
                on ? neonGlow(ACCENT, 3) : null,
              ]}
            >
              <Text style={[styles.tabText, on && { color: colors.white }]}>{label}</Text>
            </Pressable>
          );
        })}
      </View>

      <ScrollView
        contentContainerStyle={styles.scroll}
        showsVerticalScrollIndicator={false}
      >
        <View style={[styles.badge, neonGlow(colors.orange, 4)]}>
          <Text style={styles.badgeText}>DRAFT — NOT FINAL LEGAL COPY</Text>
        </View>
        <Text style={styles.body}>{body}</Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  decor: { ...StyleSheet.absoluteFill },
  tabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  tab: {
    borderWidth: 1,
    borderColor: withAlpha(colors.muted, 0.3),
    borderRadius: radii.compact,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: colors.card,
  },
  tabText: {
    fontFamily: fontFamilies.rajdhaniSemiBold,
    fontSize: 13,
    color: colors.muted,
  },
  scroll: { padding: 16, paddingBottom: 40, gap: 12 },
  badge: {
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: withAlpha(colors.orange, 0.5),
    backgroundColor: withAlpha(colors.orange, 0.12),
    borderRadius: radii.compact,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  badgeText: {
    fontFamily: fontFamilies.orbitronBold,
    fontSize: 10,
    letterSpacing: 1,
    color: colors.orange,
  },
  body: {
    fontFamily: fontFamilies.rajdhaniSemiBold,
    fontSize: 14,
    lineHeight: 22,
    color: colors.white,
  },
});
